#!/usr/bin/env bash

set -eo pipefail

source "$(dirname "$0")/stats-utils.sh"

stats=$(/usr/local/bin/xray api statsquery -server "$API_SERVER" -reset)
today=$(date +%F)
user_down_up=$(/usr/bin/jq -r -f "$(dirname "$0")/stats-to-user-down-up.jq" <<< "$stats")

mkdir -p "$TRAFFIC_DIR"
while IFS= read -r line; do
    if [[ -z "$line" ]]; then
        continue
    fi

    IFS=$'\t' read -r user down up <<< "$line"
    echo "[stats-collect] user: $user, down: $down, up: $up"

    mkdir -p "$TRAFFIC_DIR/$user/down" "$TRAFFIC_DIR/$user/up"
    echo "$down" >> "$TRAFFIC_DIR/$user/down/$today"
    echo "$up" >> "$TRAFFIC_DIR/$user/up/$today"
done <<< "$user_down_up"
