#!/usr/bin/env bash

set -eo pipefail

shrinkDate=${1:-$(date +%F)}

source "$(dirname "$0")/stats-utils.sh"

shrink() {
    local sum
    sum=$(sum-num-file "$1")
    echo "$sum" > "$1"
}

# shellcheck disable=SC2231 # Can contain globs. stats-shrink '2024-09-*'
for statsFile in "$TRAFFIC_DIR"/*/{down,up}/$shrinkDate; do
    if [ ! -f "$statsFile" ]; then
        continue
    fi

    echo "Shrink: ""$statsFile"
    shrink "$statsFile"
done
